# Generated by Django 4.1.1 on 2022-09-15 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dockerCompose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(max_length=4)),
                ('container_name', models.CharField(max_length=50)),
                ('command', models.CharField(max_length=200)),
                ('env', models.CharField(max_length=200)),
                ('volumes', models.CharField(max_length=200)),
                ('ports', models.IntegerField(max_length=20)),
                ('depends_on', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='dockerfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.CharField(max_length=100)),
                ('comandos', models.CharField(max_length=1000)),
            ],
        ),
    ]
