# Generated by Django 4.1.1 on 2022-09-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Containers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dockercompose',
            name='ports',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dockercompose',
            name='version',
            field=models.IntegerField(),
        ),
    ]
