# Generated by Django 4.1.1 on 2022-09-15 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Containers', '0002_alter_dockercompose_ports_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dockerfile',
            old_name='comandos',
            new_name='command',
        ),
        migrations.RenameField(
            model_name='dockerfile',
            old_name='imagem',
            new_name='image',
        ),
    ]
