# Generated by Django 4.1.1 on 2022-09-15 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Containers', '0004_alter_dockercompose_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockercompose',
            name='restart',
            field=models.CharField(default='abc', max_length=20),
            preserve_default=False,
        ),
    ]
